permalink: /:categories/:title.html
url: "http://barandogan.av.tr"
full_name: "Avukat Baran Doğan"
first_name: "Baran"
last_name: "Doğan"
blog_title: "Baran Doğan makaleleri ve dusunceleri"
author_img_name_path: "/images/users/baran.jpg"
disqus_shortname: ""
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Marmara Üniversitesi Hukuk Fakültesi’nde devam ederek 2000 yılında hukuk fakültesinden mezun olmuştur.Avukatlık stajının ardından kurduğu hukuk bürosuyla 2002 yılından beri serbest avukatlık yapmaktadır." 
twitter: "baran_dogan"
facebook: "Avukatbarandogan"
linkined_url: ""
exclude:
- README.md
- Rakefile
- post.sh
